/**
 * Curated list of Dashicons for the icon picker.
 * Full reference: https://developer.wordpress.org/resource/dashicons/
 */
export const DASHICONS = [
	// Admin / Interface
	{ slug: 'admin-home', label: 'Home' },
	{ slug: 'admin-site', label: 'Site' },
	{ slug: 'admin-site-alt3', label: 'Site Alt' },
	{ slug: 'admin-users', label: 'Users' },
	{ slug: 'admin-media', label: 'Media' },
	{ slug: 'admin-page', label: 'Page' },
	{ slug: 'admin-settings', label: 'Settings' },
	{ slug: 'admin-post', label: 'Post' },
	{ slug: 'admin-comments', label: 'Comments' },
	{ slug: 'admin-appearance', label: 'Appearance' },
	{ slug: 'admin-tools', label: 'Tools' },
	{ slug: 'admin-links', label: 'Links' },
	{ slug: 'admin-network', label: 'Network' },
	{ slug: 'admin-generic', label: 'Generic' },

	// Common
	{ slug: 'star-filled', label: 'Star' },
	{ slug: 'star-half', label: 'Star Half' },
	{ slug: 'star-empty', label: 'Star Empty' },
	{ slug: 'heart', label: 'Heart' },
	{ slug: 'flag', label: 'Flag' },
	{ slug: 'warning', label: 'Warning' },
	{ slug: 'info', label: 'Info' },
	{ slug: 'yes', label: 'Check' },
	{ slug: 'yes-alt', label: 'Check Alt' },
	{ slug: 'no', label: 'X Circle' },
	{ slug: 'no-alt', label: 'X' },
	{ slug: 'plus', label: 'Plus' },
	{ slug: 'plus-alt', label: 'Plus Circle' },
	{ slug: 'minus', label: 'Minus' },
	{ slug: 'dismiss', label: 'Dismiss' },
	{ slug: 'marker', label: 'Marker' },
	{ slug: 'lock', label: 'Lock' },
	{ slug: 'unlock', label: 'Unlock' },
	{ slug: 'search', label: 'Search' },
	{ slug: 'edit', label: 'Edit' },
	{ slug: 'trash', label: 'Trash' },
	{ slug: 'visibility', label: 'Visibility' },
	{ slug: 'hidden', label: 'Hidden' },

	// Content
	{ slug: 'book', label: 'Book' },
	{ slug: 'book-alt', label: 'Book Alt' },
	{ slug: 'calendar', label: 'Calendar' },
	{ slug: 'calendar-alt', label: 'Calendar Alt' },
	{ slug: 'clock', label: 'Clock' },
	{ slug: 'tag', label: 'Tag' },
	{ slug: 'category', label: 'Category' },
	{ slug: 'format-image', label: 'Image' },
	{ slug: 'format-gallery', label: 'Gallery' },
	{ slug: 'format-video', label: 'Video' },
	{ slug: 'format-audio', label: 'Audio' },
	{ slug: 'format-chat', label: 'Chat' },
	{ slug: 'format-quote', label: 'Quote' },
	{ slug: 'format-aside', label: 'Aside' },
	{ slug: 'format-status', label: 'Status' },

	// Social / Communication
	{ slug: 'share', label: 'Share' },
	{ slug: 'share-alt', label: 'Share Alt' },
	{ slug: 'email', label: 'Email' },
	{ slug: 'email-alt', label: 'Email Alt' },
	{ slug: 'phone', label: 'Phone' },
	{ slug: 'megaphone', label: 'Megaphone' },
	{ slug: 'bell', label: 'Bell' },
	{ slug: 'groups', label: 'Groups' },
	{ slug: 'networking', label: 'Networking' },
	{ slug: 'twitter', label: 'Twitter' },
	{ slug: 'facebook', label: 'Facebook' },
	{ slug: 'facebook-alt', label: 'Facebook Alt' },
	{ slug: 'rss', label: 'RSS' },

	// Arrows
	{ slug: 'arrow-up-alt', label: 'Arrow Up' },
	{ slug: 'arrow-down-alt', label: 'Arrow Down' },
	{ slug: 'arrow-left-alt', label: 'Arrow Left' },
	{ slug: 'arrow-right-alt', label: 'Arrow Right' },
	{ slug: 'arrow-up-alt2', label: 'Arrow Up 2' },
	{ slug: 'arrow-down-alt2', label: 'Arrow Down 2' },
	{ slug: 'arrow-left-alt2', label: 'Arrow Left 2' },
	{ slug: 'arrow-right-alt2', label: 'Arrow Right 2' },

	// Objects
	{ slug: 'lightbulb', label: 'Lightbulb' },
	{ slug: 'shield', label: 'Shield' },
	{ slug: 'shield-alt', label: 'Shield Alt' },
	{ slug: 'award', label: 'Award' },
	{ slug: 'thumbs-up', label: 'Thumbs Up' },
	{ slug: 'thumbs-down', label: 'Thumbs Down' },
	{ slug: 'download', label: 'Download' },
	{ slug: 'upload', label: 'Upload' },
	{ slug: 'cloud', label: 'Cloud' },
	{ slug: 'clipboard', label: 'Clipboard' },
	{ slug: 'paperclip', label: 'Paperclip' },
	{ slug: 'hammer', label: 'Hammer' },
	{ slug: 'camera', label: 'Camera' },
	{ slug: 'camera-alt', label: 'Camera Alt' },
	{ slug: 'images-alt', label: 'Images' },
	{ slug: 'location', label: 'Location' },
	{ slug: 'location-alt', label: 'Location Alt' },
	{ slug: 'store', label: 'Store' },
	{ slug: 'cart', label: 'Cart' },
	{ slug: 'businessman', label: 'Businessman' },
	{ slug: 'businesswoman', label: 'Businesswoman' },
	{ slug: 'building', label: 'Building' },
	{ slug: 'portfolio', label: 'Portfolio' },
	{ slug: 'art', label: 'Art' },
	{ slug: 'id', label: 'ID' },
	{ slug: 'id-alt', label: 'ID Alt' },
	{ slug: 'universal-access', label: 'Accessibility' },
	{ slug: 'universal-access-alt', label: 'Accessibility Alt' },
	{ slug: 'database', label: 'Database' },
	{ slug: 'money-alt', label: 'Money' },

	// Devices
	{ slug: 'desktop', label: 'Desktop' },
	{ slug: 'laptop', label: 'Laptop' },
	{ slug: 'tablet', label: 'Tablet' },
	{ slug: 'smartphone', label: 'Smartphone' },

	// Charts
	{ slug: 'chart-bar', label: 'Chart Bar' },
	{ slug: 'chart-line', label: 'Chart Line' },
	{ slug: 'chart-pie', label: 'Chart Pie' },
	{ slug: 'chart-area', label: 'Chart Area' },

	// Editor
	{ slug: 'editor-bold', label: 'Bold' },
	{ slug: 'editor-italic', label: 'Italic' },
	{ slug: 'editor-ul', label: 'List' },
	{ slug: 'editor-ol', label: 'Ordered List' },
	{ slug: 'editor-quote', label: 'Editor Quote' },
	{ slug: 'editor-code', label: 'Code' },
	{ slug: 'editor-table', label: 'Table' },
	{ slug: 'editor-paragraph', label: 'Paragraph' },
];
